version: '3'
services:
  addictive-keycloak:
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:17.0.0
    container_name: addictive-keycloak
    depends_on:
      - postgres
    ports:
      - 9080:8080
      - 8443:8443
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      #- KEYCLOAK_WELCOME_THEME=viblio-theme
      - PROXY_ADDRESS_FORWARDING=true
      ## admin login:pass is admin:123
    volumes:
      - keycloak-data-volume:/var/lib/keycloak/data
      - ./keycloak/conf/:/opt/keycloak/conf/
    command: ["start-dev", "--db=postgres", "--db-url-host=postgres", "--db-url=jdbc:postgresql://postgres/keycloak", "--db-username=addictive", "--db-password=addictive", "--proxy=edge", "--hostname=keycloak.addictive.local"] #, "--hostname-strict-backchannel=true"

  addictive-keystone:
    container_name: addictive-keystone
    image: node:16.17
    ports:
      - 3000:3000
    # user: "node"
    working_dir: /home/node/app/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:addictive@addictive:5432/addictive
      - SESSION_SECRET=catopleba89catopleba89catopleba89catopleba89catopleba89catopleba89v
      - AUTH_DOMAIN=http://${KEYCLOAK_DOMAIN}/realms/addictive
      - AUTH_DOMAIN_INTERNAL=http://addictive-keycloak:8080/realms/addictive
      - AUTH_CLIENT_ID=todo-app-backend
      - AUTH_CLIENT_SECRET=QDUa1BxHO0wiznAtkvTDvO4QnEpLnCJH
      - NEXTAUTH_URL=http://keystone.addictive.local/admin/api/auth
      - NEXTAUTH_URL_INTERNAL=http://addictive-keystone:3000/admin/api/auth

    volumes:
        - ./keystone:/home/node/app
        - keystone-node_modules:/home/node/app/node_modules
    command: ["yarn", "dev"]
    links:
        - postgres

  # todo-app:
  #   container_name: todo-app
  #   image: node:16.17
  #   ports:
  #     - 7070:7070
  #   # user: "node"
  #   working_dir: /home/node/app
  #   environment:
  #     - NODE_ENV=development
  #     # - DATABASE_URL=postgres://postgres:addictive@addictive:5432/addictive
  #     - PORT=7070
  #     - AUTH_DOMAIN=http://${KEYCLOAK_DOMAIN}/realms/addictive
  #     - AUTH_CLIENT_ID=todo-app-backend
  #     - AUTH_CLIENT_SECRET=QDUa1BxHO0wiznAtkvTDvO4QnEpLnCJH
  #     - AUTH_REALM=${AUTH_REALM}
  #     - AUTH_DISCOVERY_URL=http://keycloak:8080
  #     - APP_URL=http://${TODO_DOMAIN}
  #   volumes:
  #     - ./todo-app/data:/home/node/data
  #     - ./todo-app/app:/home/node/app
  #     - todo-app-node_modules:/home/node/app/node_modules
  #   command: ["yarn", "dev"]
  #   links:
  #       - postgres

  addictive-proxy:
    restart: unless-stopped
    image: nginx:1.21.6-alpine
    container_name: addictive-proxy
    depends_on:
      - "addictive-keycloak"
      #- "todo-app"
      - "addictive-keystone"
    environment:
      -  KEYCLOAK_DOMAIN=${KEYCLOAK_DOMAIN}
      -  TODO_DOMAIN=${TODO_DOMAIN}
      -  KEYSTONE_DOMAIN=${KEYSTONE_DOMAIN}
      -  KEYCLOAK_CONTAINER=addictive-keycloak
      -  KEYCLOAK_CONTAINER_PORT=8080
      -  KEYSTONE_CONTAINER=addictive-keystone
      -  KEYSTONE_CONTAINER_PORT=3000
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/templates_no_https:/etc/nginx/templates:ro


  # production-server:
  #   container_name: service-name
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #       - .:/app
  #   environment:
  #       - DATABASE_URL=postgres://user:password@postgres:5432/database-name
  #   ports:
  #   - "3000:3000"
  #   command: ["./dumb-init", "yarn", "start"]
  #   links:
  #       - postgres

  postgres:
    image: "postgres:12"
    container_name: "postgres"
    environment:
        - POSTGRES_USER=addictive
        - POSTGRES_PASSWORD=addictive
        - POSTGRES_DB=addictive
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
  keycloak-data-volume:
  keystone-node_modules:
  todo-app-node_modules:
