version: '3'
services:
  keycloak:
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:17.0.0
    container_name: keycloak
    depends_on:
      - postgres
    ports:
      - 9080:8080
      - 8443:8443
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      #- KEYCLOAK_WELCOME_THEME=viblio-theme
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - keycloak-data-volume:/var/lib/keycloak/data
 
      - ./keycloak/conf/:/opt/keycloak/conf/
    command: ["start-dev", "--db=postgres", "--db-url-host=postgres", "--db-url=jdbc:postgresql://postgres/keycloak", "--db-username=addictive", "--db-password=addictive", "--proxy=edge"]

  casdoor:
    restart: always
    image: casbin/casdoor
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      RUNNING_IN_DOCKER: "true"
    ## admin login:pass is admin:123
    volumes:
      - ./casdoor/conf/app.conf:/conf/app.conf

  keystone:
    container_name: keystone
    image: node:16.17
    ports:
      - 3000:3000
    # user: "node"
    working_dir: /home/node/app/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:addictive@addictive:5432/addictive
    volumes:
        - ./keystone:/home/node/app
        - keystone-node_modules:/home/node/app/node_modules
    command: ["yarn", "dev"]
    links:
        - postgres

  # production-server:
  #   container_name: service-name
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #       - .:/app
  #   environment:
  #       - DATABASE_URL=postgres://user:password@postgres:5432/database-name
  #   ports:
  #   - "3000:3000"
  #   command: ["./dumb-init", "yarn", "start"]
  #   links:
  #       - postgres

  postgres:
    image: "postgres:12"
    container_name: "postgres"
    environment:
        - POSTGRES_USER=addictive
        - POSTGRES_PASSWORD=addictive
        - POSTGRES_DB=addictive
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
  keycloak-data-volume:
  keystone-node_modules:
